#########################
#        SupraAPI       #
#        v 0.0.1        #
#########################

channels:
  message: "SupraAPI:Message"

sql:
  host: "127.0.0.1"
  port: "3306"
  database: "database"
  username: "root"
  password: "root"
  enable: true

jedis:
  host: "127.0.0.1"
  password: "root"
  enable: true

mongodb:
  host: "127.0.0.1"
  port: "27017"
  username: "root"
  password: "root"
  database: "database"
  enable: true

rabbitmq:
  host: "127.0.0.1"
  port: "5672"
  username: "root"
  password: "root"
  enable: true