#########################
#        SupraAPI       #
#        v 0.0.1        #
#########################

channels:
  message: "SupraAPI:Message"

sql:
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""
  enable: false

jedis:
  host: ""
  password: ""
  enable: false

mongodb:
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""
  enable: false

rabbitmq:
  host: ""
  port: ""
  username: ""
  password: ""
  enable: false