#########################
#        SupraAPI       #
#        v 0.0.1        #
#########################

sql:
  host: ""
  port: ""
  database: ""
  username: ""
  password: ""
  enable: false

jedis:
  host: ""
  password: ""
  enable: false

mangodb:
  host: ""
  port: ""
  username: ""
  password: ""
  enable: false